### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by mlodic** [certego/.github#112]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: syphar/restore-virtualenv, syphar/restore-pip-download-cache, syphar/restore-virtualenv, syphar/restore-pip-download-cache, syphar/restore-pip-download-cache, syphar/restore-pip-download-cacheShow less

**Comment by acocheo** [comment]
Fixed our side.

But problem [persists](https://github.com/certego/.github/actions/runs/3241372496) for external actions. In particular in all [syphar](https://github.com/syphar/restore-virtualenv) actions that we use for caching.
3 possibilities @0ssigeno :
- open issues to syphar
- fork his work
- don't care

**Comment by acocheo** [comment]
[Fix in progress](https://github.com/syphar/restore-virtualenv/issues/588) by author
