### ISSUE TITLE
Add `use_pyupgrade`

### ISSUE THREAD

**Issue by mlodic** [certego/.github#119]
Add pyupgrade both on pre-commit and tests:

      # Upgrade to the latest Python syntax with https://github.com/asottile/pyupgrade
      - uses: install-pinned/pyupgrade@0bb513444c8ff7ce06d3f76e271d1ee7028c3640
      - name: Run pyupgrade
        run: |  
          shopt -s globstar
          pyupgrade --exit-zero-even-if-changed --py310-plus **/*.py

**Comment by 0ssigeno** [comment]
Not implementing this till the linter allows a `--check`, or `--dry-run`
