### ISSUE TITLE
`How to` documentation

### ISSUE THREAD

**Issue by acocheo** [certego/.github#5]
Some docs describing how to use starters are mandatory.

## Possible solutions
- Read the Docs
- Markdown hypertext inside this repo
- Github wiki
- Google docs + link

**Comment by acocheo** [comment]
Some infos in documentation:
- How to import and configure starters
- (future) How to use config submodule
- Fix npm `scripts` names for linters/tests

**Comment by 0ssigeno** [comment]
For subtree implementation, we need the documentation:

- How to use subtree on the repo  to import the .github
-  How to merge conflict with upstream
- Specify the possibility to customize the configurations

**Comment by acocheo** [comment]
Write all in READMEs
