### ISSUE TITLE
Implement `services`

### ISSUE THREAD

**Issue by acocheo** [certego/.github#6]
Add `services` part.
Select which execute via configs, or always start all?

**Comment by 0ssigeno** [comment]
My solution:

Have two different jobs: 
- tests_with_services
- tests_without_services

The right test will be executed based on the input `use_services`.
The `steps` of the two jobs will be exactly the same. The `tests_with_services` will have obviously a new setup step where the services are actually build.


In the future we can transform the `steps` in a composite action that will be called by the two `jobs`, meaning that we won't need to reuse any code. I think we can do this in a second moment.

This solution will not require to **always** have the long setup that services requires but does not allow to freely configure them: GA does not allow any `if` conditions there, and I did not find a straightforward solution to do this.
