### ISSUE TITLE
Print debug informations for detect_changes

### ISSUE THREAD

**Issue by eugenioseveri** [certego/.github#83]
I suggest to print, for each step (backend, frontend) of the *detect_changes* action, the following data for debugging purposes:
* the directory the diff ran on;
* the number of changed lines.

**Comment by 0ssigeno** [comment]
- The diff is not run **in** a directory, but is done through `git diff`.
- I see no use case where, even in debugging mode, you should need to know the number of changed lines **in** the CI.

If you need to debug and know which files have been detected as changed, you can rerun the job in [debug mode](https://github.community/t/outputs-are-invisible/115975/3)

**Comment by eugenioseveri** [comment]
I didn't know about additional messages in debug mode. I'll try it, maybe it can cover this use case.
Anyway, this is a use case for the number of changed lines: last week there was a new bug in the production CI in the "detect-changes" step which caused the tests not to run. It would have been easier to debug if we had known that changes not only weren't detected, but the variable was not initialized (because it was not exported through reusable workflows). Adding this info just requires a simple "echo" command of that variable.

**Comment by 0ssigeno** [comment]
I still don't see how know the number of changed lines will make any that you described easier.
Do you mean the **files** that `detect_changes` detected for both backend and frontend?

**Comment by eugenioseveri** [comment]
In last week's case, we assumed there were no bugs in the workflow (since the previous version worked). Having the number of changed lines would have helped identifying the bug earlier, because that variable was not initialized. But also having the list of changed files could be useful to check what changes the action detects. 😛
