### ISSUE TITLE
Coverage summary not human readable

### ISSUE THREAD

**Issue by mlodic** [certego/.github#95]
Right now, the coverage result is not readable so it is not usable properly.

The best thing should be to write that result in a table form because the result are basically made to be rendered as a table.

A faster implementation could be to just show the % values and remove all the other ones, like it was previously available in Quokka before this repo even existed. At least, in that way, we would be able to easily understand which files are not tested. Otherwise right now it is impossible to understand.

**Comment by acocheo** [comment]
Duplicate #42
